name: Deploy to Backend Server A (Main)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server A
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST_1 }} << EOF
        cd /var/www/honors-web-app || exit

        git fetch origin
        git reset --hard origin/main

        echo "DATABASE_URL=${{ secrets.DB_URL }}" > .env
        echo "NEXTAUTH_URL=http://${{ secrets.HOST_1 }}" >> .env
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
        echo "NODE_ENV=production" >> .env
        echo "PORT=3000" >> .env

        npm install --legacy-peer-deps
        npm install @next/swc-linux-x64-gnu

        npx prisma generate
        npm run build

        pm2 delete next-app || true
        pm2 start "npm run start -- -p 3000" --name next-app
        pm2 save
        EOF
